### ISSUE TITLE
오류 수정.... 제발....

### ISSUE THREAD

**Issue by newhajinyoon** [exte0427/wall#2]
중독성이 너무 있어.... 하지만 오류가.... 으어ㅓ

**Comment by exte0427** [comment]
![tenor](https://user-images.githubusercontent.com/62054524/90148925-dbd64980-ddbe-11ea-9e3a-c71f9c0c0a2c.gif)

**Comment by newhajinyoon** [comment]
![image](https://user-images.githubusercontent.com/61103309/90149088-0de7ab80-ddbf-11ea-9978-59a7c4f85794.png)

**Comment by exte0427** [comment]
![3tb4vxbbfyh21](https://user-images.githubusercontent.com/62054524/90149138-1e982180-ddbf-11ea-9dfa-c450ca065168.jpg)
